### ISSUE TITLE
Audio Output?

### ISSUE THREAD

**Issue by benjgorman** [Venetian/ofxSpectrogramAudioInput#1]
Would it be possible to use this spectrogram to do audio output? As in generating a spectrogram from playing sound?

**Comment by Venetian** [comment]
Yes, did you try this?
You're looking for real time spectrogram?

**Comment by benjgorman** [comment]
Ah yes, sorry I wasn't clear I meant as in playing a wav file. I think I've worked it out however, just load the file using libsndfile and use audioOutput method of ofSoundStream?

**Comment by Venetian** [comment]
yes, I think I need the problem framed more. For instance, I have 
openframeworks code for displaying a spectrogram of a playing soundfile.
What's it for?

**Comment by benjgorman** [comment]
Ah yes that would be exactly what I was looking to do. I'm just looking to have a spectrogram of a soundfile to test out some visualisation techniques.

**Comment by Venetian** [comment]
running mac?

and you don;t want software like sonic viusaliser, you wnat to write 
your own visualisation?

**Comment by benjgorman** [comment]
Yup using xcode. Yeah I want to be able to control the output and overlay it with some other graphics etc. Hence why I'm trying to roll my own.

**Comment by Venetian** [comment]
so I was just looking through what's on my computer here

you need:
1. load a soundfile - eg with libsndfile? - and sequentially process all 
the samples
2. process the FFT and store magnitude for each frame of audio
3. display the spectrogram, maybe based off where you are in the playing 
file

which bits do you have?

whilst it could do with a revision I hgave some of 1.
the real time version you have has 2 and 3.

for 1.: eg in ofxaudioFileLoader there's this read code:

void ofxSoundFileLoader::readAudio(){

```
 audioHolder.audioVector.clear();

 // HERE IS THE CLASSIC LOADING FILE CODE
 //DEALS WITH MORE THAN MONO
 int channels = sfinfo.channels;
 int blocksize = FRAMESIZE;

 float buf [channels * blocksize] ;
 int k, m, readcount ;

 DoubleVector d;
 while ((readcount = sf_readf_float (infile, buf, blocksize)) > 0){
     for (k = 0 ; k < readcount ; k++){
         d.clear();
         for (m = 0 ; m < channels ; m++){
             d.push_back(buf [k * channels + m]);
             //         fprintf (outfile, " % 12.10f", buf [k * 
```

channels + m]) ;
                 //         fprintf (outfile, "\n") ;
                 if (m == 0){
                     //makes the vector hold the mono file - the left 
channel
                     audioHolder.audioVector.push_back(buf[k \* channels 
- 0]);
                   frame[k] = buf[k*channels + 0];
               }
  
  ```
       }
   audioHolder.audioMatrix.push_back(d);
       //storing the full soundfile in multiple channels in the 
  ```
  
  audioMatrix
       }
  
  ```
   //could call this here
  ```
  
   //    onsetDetect->processFrame(&frame[0], blocksize);
  
   }//end readcount
  
   //printf("audio vector size is %i\n", (int) 
  audioHolder.audioVector.size());
   audioHolder.length = (int) audioHolder.audioVector.size();
   totalNumberOfFrames = audioHolder.length;
  }

**Comment by benjgorman** [comment]
That's exactly what I was looking for, I didn't realise you have ofxaudioFileLoader, Cheers for your time!

**Comment by benjgorman** [comment]
I realised I closed this. But, I still can't get the output I'm looking for, I've tried to adapt your real time spectrogram to play a soundfile. I have got the soundfile to play and I can get some output on the spectrogram.

But it does not look anything like the spectrogram which is displayed if I use the version with audio input. Am I doing something wrong? I suspect I am getting the wrong output values.

In the realtime version, I am using this callback to get the input from the microphone and add it to the FFT.

void testApp::audioIn(float \* input, int bufferSize, int nChannels){

```
float curVol = 0.0;

// samples are "interleaved"
int numCounted = 0;

//lets go through each sample and calculate the root mean square which is a rough way to calculate volume
for (int i = 0; i < bufferSize; i++){
    left[i]     = input[i*2]*0.5;

    addToFFT(left[i]);


    right[i]    = input[i*2+1]*0.5;

    curVol += left[i] * left[i];
    curVol += right[i] * right[i];
    numCounted+=2;
}


//this is how we get the mean of rms :)
curVol /= (float)numCounted;

// this is how we get the root of rms :)
curVol = sqrt( curVol );

smoothedVol *= 0.93;
smoothedVol += 0.07 * curVol;

bufferCounter++;
```

}

And then when I am trying to play a soundfile and see the spectrogram I am using this callback.

//--------------------------------------------------------------
void testApp::audioRequested (float \* output, int bufferSize, int nChannels)
{

```
if (audioPlaying==true)
{
    float curVol = 0.0;

    // samples are "interleaved"
    int numCounted = 0;

    //lets go through each sample and calculate the root mean square which is a rough way to calculate volume
    for (int i = 0; i < bufferSize; i++)
    {
        //int test = fileLoader.audioHolder.playPosition;
        output[i*nChannels] =  fileLoader.audioHolder.audioMatrix[fileLoader.audioHolder.playPosition][0];

        left[i] = output[i*nChannels];

        addToFFT(left[i]);

        output[i*nChannels+1] =  fileLoader.audioHolder.audioMatrix[fileLoader.audioHolder.playPosition][0];
        right[i] = output[i*nChannels+1];

        curVol += left[i] * left[i];
        curVol += right[i] * right[i];
        numCounted+=2;

    }

    //this is how we get the mean of rms :)
    curVol /= (float)numCounted;

    // this is how we get the root of rms :)
    curVol = sqrt( curVol );

    smoothedVol *= 0.93;
    smoothedVol += 0.07 * curVol;

    bufferCounter++;
}
```

}

I suspect this  fileLoader.audioHolder.audioMatrix[fileLoader.audioHolder.playPosition][0]; is perhaps not the way to access the correct audio data I need? But I'm not sure. I also tried accessing the frames through audioVector but that didn't seem correct either. Any help would be appreciated.

**Comment by benjgorman** [comment]
Worked it out!
